# Generated by Django 5.0.3 on 2024-03-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('firstOption', models.CharField(max_length=30)),
                ('secondOption', models.CharField(max_length=30)),
                ('thirdOption', models.CharField(max_length=30)),
                ('firstOptionCount', models.IntegerField(default=0)),
                ('secondOptionCount', models.IntegerField(default=0)),
                ('thirdOptionCount', models.IntegerField(default=0)),
            ],
        ),
    ]
