# Generated by Django 5.0.3 on 2024-03-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='fourthOptionCount',
            field=models.IntegerField(default=0),
        ),
    ]
